//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingITProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class employer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employer()
        {
            this.rents = new HashSet<rent>();
        }
    
        public int employer_id { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string middlename { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int post_id { get; set; }
        public string phone { get; set; }
        public string sex { get; set; }
        public byte[] photo { get; set; }
    
        public virtual poste poste { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rent> rents { get; set; }
    }
}
