//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingITProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class getHallsView
    {
        public int status_id { get; set; }
        public string title { get; set; }
        public int floor { get; set; }
        public string hall_number { get; set; }
        public int mall_id { get; set; }
        public decimal area { get; set; }
        public int status { get; set; }
        public decimal value_added_factor { get; set; }
        public decimal cost { get; set; }
    }
}
