//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingITProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mall
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mall()
        {
            this.halls = new HashSet<hall>();
        }
    
        public int mall_id { get; set; }
        public string title { get; set; }
        public int status_id { get; set; }
        public int halls_count { get; set; }
        public string address { get; set; }
        public decimal cost { get; set; }
        public decimal value_added_factor { get; set; }
        public int floors_count { get; set; }
        public byte[] icon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hall> halls { get; set; }
        public virtual status status { get; set; }
    }
}
