//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingITProject.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KingITDBEntities : DbContext
    {
        public KingITDBEntities()
            : base("name=KingITDBEntitiesD")
        {
        }
        public KingITDBEntities(string s)
            : base(s)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<employer> employers { get; set; }
        public virtual DbSet<hall> halls { get; set; }
        public virtual DbSet<mall> malls { get; set; }
        public virtual DbSet<poste> postes { get; set; }
        public virtual DbSet<rent> rents { get; set; }
        public virtual DbSet<status> statuses { get; set; }
        public virtual DbSet<tenant> tenants { get; set; }
        public virtual DbSet<getHallsView> getHallsViews { get; set; }
    
        [DbFunction("KingITDBEntities1", "getHalls")]
        public virtual IQueryable<getHalls_Result> getHalls(Nullable<int> current)
        {
            var currentParameter = current.HasValue ?
                new ObjectParameter("current", current) :
                new ObjectParameter("current", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<getHalls_Result>("[KingITDBEntities1].[getHalls](@current)", currentParameter);
        }
    
        [DbFunction("KingITDBEntities1", "getMalls")]
        public virtual IQueryable<getMalls_Result> getMalls()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<getMalls_Result>("[KingITDBEntities1].[getMalls]()");
        }
    
        public virtual int change_rent_date()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("change_rent_date");
        }
    }
}
