//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingITProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rent
    {
        public int rent_id { get; set; }
        public int tenant_id { get; set; }
        public int mall_id { get; set; }
        public int employer_id { get; set; }
        public string hall_number { get; set; }
        public int status_id { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
    
        public virtual employer employer { get; set; }
        public virtual hall hall { get; set; }
        public virtual status status { get; set; }
        public virtual tenant tenant { get; set; }
    }
}
