//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingITProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class statMallView
    {
        public string title { get; set; }
        public string address { get; set; }
        public Nullable<int> free_halls_count { get; set; }
        public int halls_count { get; set; }
        public Nullable<int> rented_halls_count { get; set; }
        public Nullable<decimal> free_halls_area { get; set; }
        public Nullable<decimal> avg_halls_cost { get; set; }
        public int mall_id { get; set; }
    }
}
